# Generated by Django 3.1 on 2020-08-05 17:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='facebook_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.facebook_image_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload_to),
        ),
    ]
